# Generated by Django 4.2.7 on 2024-03-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='classification',
            field=models.SmallIntegerField(choices=[(5, '日常'), (4, '娱乐'), (6, '测试'), (2, '社会'), (3, '政治'), (1, '体育')], default=1, verbose_name='分类'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='classification',
            field=models.SmallIntegerField(choices=[(5, '日常'), (4, '娱乐'), (6, '测试'), (2, '社会'), (3, '政治'), (1, '体育')], verbose_name='分类'),
        ),
    ]
