# Generated by Django 4.2.7 on 2024-03-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamics', '0002_tag_classification_alter_dynamic_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='dynamic',
            field=models.ManyToManyField(to='dynamics.dynamic'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='classification',
            field=models.SmallIntegerField(choices=[(3, '政治'), (6, '测试'), (1, '体育'), (2, '社会'), (5, '日常'), (4, '娱乐')], verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='classification',
            field=models.SmallIntegerField(choices=[(3, '政治'), (6, '测试'), (1, '体育'), (2, '社会'), (5, '日常'), (4, '娱乐')], verbose_name='分类'),
        ),
    ]
